version: '3'

services:
  strapi:
    user: root
    container_name: portfolio-strapi
    image: strapi/strapi
    environment:
      - NODE_ENV=production
    ports:
      - 1337:1337
    volumes:
      - ./:/srv/app

  frontend:
    container_name: portfolio-frontend
    restart: unless-stopped
    build: ./clientApp
    environment:
       - VITE_STRAPI_URL=${VITE_STRAPI_URL}
       - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    links:
       - "strapi"
    ports:
      - '3000:3000'
