name: Docker Image CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: touch clientApp/.env && echo SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} >> clientApp/.env && echo VITE_PUBLIC_STRAPI_URL=${{ secrets.VITE_STRAPI_URL }}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_REGISTRY }}/portfolio-frontend:latest ./clientApp && docker build -t ${{ secrets.DOCKER_REGISTRY }}/portfolio-backend:latest .
      - name: Docker login
        run:  docker login ${{ secrets.DOCKER_REGISTRY }}/v2 -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push images to Dockerhub
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/portfolio-frontend:latest && docker push ${{ secrets.DOCKER_REGISTRY }}/portfolio-backend:latest
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
           cd ~/docker/containers/portfolio
           docker-compose down
           docker-compose pull
           sleep 10s
           docker-compose up -d
